version: '3.9'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3


  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on: 
      elasticsearch:
        condition: service_healthy


  filebeat-raw:
    image: docker.elastic.co/beats/filebeat:8.3.0
    container_name: filebeat-raw
    command: /bin/sh -c "filebeat -e --strict.perms=false --once"
    secrets:
      - source: filebeat-raw.yml
        target: /usr/share/filebeat/filebeat.yml
      - source: apache_logs.txt
        target: /tmp/apache_logs.txt
      - source: raw-template.json
        target: /usr/share/filebeat/raw-template.json        
    depends_on: 
      elasticsearch:
        condition: service_healthy


  filebeat-apache:
    image: docker.elastic.co/beats/filebeat:8.3.0
    container_name: filebeat-apache
    command: /bin/sh -c "filebeat -e setup --pipelines --strict.perms=false --modules apache; filebeat -e --strict.perms=false --once"
    secrets:
      - source: filebeat-apache.yml
        target: /usr/share/filebeat/filebeat.yml
      - source: apache_logs.txt
        target: /tmp/apache_logs.txt        
    depends_on: 
      elasticsearch:
        condition: service_healthy


secrets:
  filebeat-raw.yml:
    file: ./filebeat-raw.yml
  raw-template.json:
    file: ./raw-template.json    
  filebeat-apache.yml:
    file: ./filebeat-apache.yml    
  apache_logs.txt:
    file: ./apache_logs.txt    

